# POST http://localhost:2000/add-product HTTP/1.1
# content-type: application/json

# {
#     "product-id": 509,
#     "name": "ALTO ROUGE",
#     "image": "https://quenchproducts-prod.s3-eu-west-3.amazonaws.com/products/images/000/000/509/medium/Alto_Rouge.jpg?1568735432",
#     "category": "wines",
#     "type": "red",
#     "subCategory": "MERLOT",
#     "volume": "750ml",
#     "price": 115.95,
#     "description": "This velvety red is a true Cape legend, medium bodied with a tantalizing bouquet of red currant, almond, and cedar wood and vanilla. This blend of Cabernet Franc, Cabernet Sauvignon, Merlot, Shiraz and Petit Verdot offers a long spicy finish"
# }
GET http://localhost:2000/shop?category=beer

# PATCH  http://localhost:2000/update-post HTTP/1.1
# content-type: application/json

# {
#     "title": "wine",
#     "description": "Best wine!",
#     "image": "wine url"
# }
# DELETE http://localhost:2000/delete-post/wine HTTP/1.1